name: 'Test'
on: [push]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Begin
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Start tests
        run: |          
          chmod +x start.sh
          ./start.sh